[server]
headless = true
port = 8501
baseUrlPath = valohai.cloud$VH_DEFAULT_PREFIX
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = valohai.cloud$VH_DEFAULT_PREFIX
serverPort = 80